workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: 3.24.0
    scripts:
      - name: Get Flutter packages
        script: |
          cd flutter_billing_app-main
          flutter pub get
      - name: Build runner
        script: |
          cd flutter_billing_app-main
          dart run build_runner build --delete-conflicting-outputs
      - name: Build APK
        script: |
          cd flutter_billing_app-main
          flutter build apk --release --no-shrink
    artifacts:
      - flutter_billing_app-main/build/app/outputs/flutter-apk/app-release.apk
